name: CI/CD Pipeline - Pet-Clinic
 ## This workflow is triggered on push to the dev branch and on pull request to the main branch. 
 ## It performs the following steps:
    # 1. Gitleaks Secret Scan: Scans the repository for any secrets or sensitive information.
    # 2. Build: Compiles and packages the application, skipping tests, and uploads the build artifact. 
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]
 
### The Global Environment Variables are defined here and can be used in all the jobs in this workflow.###
env:
  JAVA_VERSION: '25'
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_PROJECT_KEY: ${{ vars.SONAR_PROJECT_KEY }}
  SONAR_ORGANIZATION: ${{ vars.SONAR_ORGANIZATION }}
  VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
  VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
  VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
  VAULT_JFROG_PATH: secrets/creds/jfrog
  JFROG_URL: ${{ secrets.JFROG_URL }}
  JFROG_REPO: 'mat_petclinic_cicd'
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
  ECS_SERVICE: ${{ secrets.ECS_SERVICE }}
 
## The jobs section defines the individual jobs that will be executed in this workflow. 
## Each job runs in its own virtual environment and can have dependencies on other jobs.
## The gitleaks job is responsible for scanning the repository for secrets, while the build job compiles
## and packages the application. The build job depends on the successful completion of the gitleaks job.
jobs:
  gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
 
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
## The build job is responsible for compiling and packaging the application. 
## It runs on an Ubuntu virtual environment and requires the successful completion 
## of the gitleaks job. The build job performs the following steps:
    ## 1. Checkout code: Checks out the code from the repository.
    ## 2. Set up JDK: Sets up the Java Development Kit (JDK) using the specified version from the environment variable.
    ## 3. Compile and package: Compiles and packages the application using Maven, skipping tests to speed up the build process.
    ## 4. Upload build artifact: Uploads the generated JAR file as an artifact for later use
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: gitleaks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
 
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven
 
      - name: Compile and package (skip tests)
        run: mvn -B clean package -DskipTests
 
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
          retention-days: 1
          
## The test job is responsible for running unit tests on the application.
## It runs on an Ubuntu virtual environment and requires the successful completion of the build job.
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven
 
      - name: Run unit tests
        run: mvn -B test
 
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/
          if-no-files-found: ignore

### The sonarQube-scan job is responsible for performing code analysis using SonarQube.
### It runs on an Ubuntu virtual environment and requires the successful completion of the test job.   
### The sonarQube-scan job performs the following steps:
    ## 1. Checkout code: Checks out the code from the repository.
    ## 2. Set up JDK: Sets up the Java Development Kit (JDK) using the specified version from the environment variable.
    ## 3. Cache SonarCloud packages: Caches SonarCloud packages to speed up subsequent runs.
    ## 4. Compile project for analysis: Compiles the project without running tests to prepare for code analysis.
    ## 5. SonarQube code analysis: Performs code analysis using SonarQube with the specified project key and organization.
    ## 6. SonarCloud Quality Gate Check: Checks the quality gate status and fails the job if the quality gate is not passed.


  sonarQube-scan:
    name: SonarQube-Scan
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
 
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven
 
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
 
      - name: Compile project for analysis
        run: mvn -B compile -DskipTests
 
      - name: SonarQube code analysis
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ env.SONAR_ORGANIZATION }}
            -Dsonar.java.binaries=target/classes
 
    #   - name: SonarCloud Quality Gate Check
    #     id: quality-gate
    #     uses: phwt/sonarqube-quality-gate-action@v1
    #     with:
    #       sonar-project-key: ${{ env.SONAR_PROJECT_KEY }}
    #       sonar-host-url: https://sonarcloud.io
    #       sonar-token: ${{ env.SONAR_TOKEN }}
    #       github-token: ${{ secrets.GITHUB_TOKEN }}
    #       branch: dev
    #       fail-on–quality-gate-error: true


# The trivy-scan job is responsible for performing a security scan using Trivy.
# It runs on an Ubuntu virtual environment and requires the successful completion of the sonarQube-scan job. The trivy-scan job performs the following steps:
# 1. Checkout code: Checks out the code from the repository.
# 2. Set up JDK: Sets up the Java Development Kit (JDK) using the specified version from the environment variable.
# 3. Populate Maven cache: Resolves project dependencies and populates the Maven cache to speed up subsequent builds
# 4. Download build artifact: Downloads the previously uploaded build artifact (JAR file)
# 5. Run Trivy filesystem scan: Performs a security scan on the filesystem using Trivy, checking for vulnerabilities with a severity of CRITICAL or HIGH. The scan results are formatted as a table, and the job continues even if vulnerabilities are found (exit code 0). Unfixed vulnerabilities are ignored to avoid failing the job.
# 6. Upload Trivy results: Uploads the Trivy scan results as an artifact for later review. This step runs regardless of the previous steps 

  trivy-scan:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    needs: sonarQube-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven
 
      - name: Populate Maven cache
        run: |
          mvn -B dependency:resolve -DskipTests \
            --no-transfer-progress
 
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target
 
      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'CRITICAL,HIGH'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
 
      - name: Upload Trivy results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs-report
          path: trivy-results.*
          if-no-files-found: ignore


# The publish job is responsible for publishing the build artifact (JAR file) to JFrog Artifactory.
# It runs on an Ubuntu virtual environment and requires the successful completion of both the sonarQube-scan and trivy-scan jobs. The publish job performs the following steps:
# 1. Download build artifact: Downloads the previously uploaded build artifact (JAR file).
# 2. Authenticate to Vault and fetch JFrog credentials: Authenticates to HashiCorp Vault using the provided credentials and retrieves the JFrog Artifactory username and password.
# 3. Setup JFrog CLI: Configures the JFrog CLI with the retrieved credentials and the specified Artifactory URL.
# 4. Upload JAR to Artifactory: Uploads the JAR file to the specified JFrog Artifactory repository. This step is executed only if the workflow is triggered by a push event to the dev branch.  
# 5. The publish job is conditional and will only run if the workflow is triggered by a push event to the dev branch. This ensures that the artifact is published only when changes are pushed to the development branch, maintaining a controlled release process.
  publish:
    name: Publish to JFrog Artifactory
    runs-on: ubuntu-latest
    needs: [ sonarQube-scan, trivy-scan ]
    if: |
      github.ref == 'refs/heads/dev' &&
      github.event_name == 'push'
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target
 
      - name: Authenticate to Vault and fetch JFrog credentials
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ env.VAULT_ADDR }}
          method: approle
          roleId: ${{ env.VAULT_ROLE_ID }}
          secretId: ${{ env.VAULT_SECRET_ID }}
          secrets: |
            ${{ env.VAULT_JFROG_PATH }} username | JF_USER ;
            ${{ env.VAULT_JFROG_PATH }} password | JF_PASSWORD
 
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ env.JFROG_URL }}
          JF_USER: ${{ env.JF_USER }}
          JF_PASSWORD: ${{ env.JF_PASSWORD }}
 
      - name: Upload JAR to Artifactory
        run: jf rt upload "target/*.jar" ${{ env.JFROG_REPO }}/


# The docker-build-push job is responsible for building a Docker image from the application code and pushing it to Amazon Elastic Container Registry (ECR).
# It runs on an Ubuntu virtual environment and requires the successful completion of the publish job. The docker-build-push job performs the following steps:
# 1. Checkout code: Checks out the code from the repository.
# 2. Configure AWS credentials: Configures the AWS credentials using the specified role and region to allow access to ECR.
# 3. Login to ECR: Logs in to the Amazon ECR registry using the configured AWS credentials.
# 4. Build, tag, and push image: Builds the Docker image, tags it with the commit SHA and 'latest', and pushes both tags to the ECR repository. This step is executed only if the workflow is triggered by a push event to the dev branch, ensuring that Docker images are built and pushed only for changes in the development branch.                             

  docker-build-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    needs: publish
    if: |
      github.ref == 'refs/heads/dev' &&
      github.event_name == 'push'
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
 
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
 
      - name: Build, tag, and push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push \
            $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag \
            $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push \
            $ECR_REGISTRY/$ECR_REPOSITORY:latest
